server:
  port: 8083 # Puerto para el microservicio de alertas

spring:
  application:
    name: ms-alertas
  datasource:
    url: jdbc:h2:mem:alertasdb
    driverClassName: org.h2.Driver

# Configuración del Circuit Breaker (Resilience4j)
resilience4j:
  circuitbreaker:
    instances:
      alertasCB:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15s

# Clave secreta para validar JWT (debe coincidir con la del API Gateway)
jwt:
  secret: "TuClaveSecretaSuperLargaYSeguraParaLaMunicipalidadValleDelSol2026"